# Generated by Django 5.0.3 on 2024-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
